"""The canonical register row, the per-market history store and the refresh rule.

Every market's register is published as **one file holding the whole history**
(the FCA's historic disclosures, the AMF's export since 2012), regenerated by
the regulator. The store therefore keeps one ``history.parquet`` per market,
replaced atomically when the published file changes, with the previous
version kept one generation back and a ``state.json`` sidecar (file date,
rows, sha256 of the raw bytes, fetch time, source). A new file with fewer
rows than the stored one is refused: a history must not shrink.

Canonical columns (one row per published position change):

- ``market``: ``uk`` (FCA), ``fr`` (AMF), ``nl`` (AFM), ``se`` (Finansinspektionen),
  ``no`` (Finanstilsynet), ``ie`` (Central Bank of Ireland), ``de`` (Bundesanzeiger);
- ``holder``, ``holder_lei`` (the AMF publishes the LEI, the FCA does not);
- ``issuer``, ``isin``;
- ``net_short_pct``: percent of the issuer's share capital, as published
  (``0.0`` where the regulator records a position falling below the
  publication threshold);
- ``position_date``: the date the position was held;
- ``published_from``: the first day the public could see the row (the AMF
  publishes it; the FCA discloses by 15:30 on the next trading day, so the
  next weekday is used, UK holidays ignored and recorded as a limit);
- ``published_to``: the AMF's end of publication, missing for the FCA and
  for rows still current;
- ``file_date``: the date of the published file the row came from.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

import pandas as pd
import pyarrow as pa

import _atomic  # type: ignore[import-not-found]

MARKETS: tuple[str, ...] = ("uk", "fr", "nl", "se", "no", "ie", "de")
#: Markets whose register is still published per holder (the UK's froze in July 2026).
LIVE_MARKETS: tuple[str, ...] = ("fr", "nl", "se", "no", "ie", "de")
PUBLICATION_THRESHOLD_PCT = 0.5

SCHEMA = pa.schema(
    [
        ("market", pa.string()),
        ("holder", pa.string()),
        ("holder_lei", pa.string()),
        ("issuer", pa.string()),
        ("isin", pa.string()),
        ("net_short_pct", pa.float64()),
        ("position_date", pa.date32()),
        ("published_from", pa.date32()),
        ("published_to", pa.date32()),
        ("file_date", pa.date32()),
    ]
)
COLUMNS: tuple[str, ...] = tuple(SCHEMA.names)


class RegisterError(Exception):
    """A transport or format problem; the message is user-facing."""


@dataclass(frozen=True)
class Parsed:
    """One parsed published file: its date and the canonical rows."""

    file_date: dt.date
    rows: pd.DataFrame
    #: Rows the parser left out (file trailers, rows without a key); reported, not stored.
    dropped: int = 0


def next_weekday(day: dt.date) -> dt.date:
    """The next Monday to Friday after ``day``."""
    out = day + dt.timedelta(days=1)
    while out.weekday() >= 5:
        out += dt.timedelta(days=1)
    return out


def canonical(frame: pd.DataFrame, *, market: str, file_date: dt.date) -> pd.DataFrame:
    """Order, type and sort a frame that already carries the canonical columns (``market``/``file_date`` filled here)."""
    out = frame.copy()
    out["market"] = market
    out["file_date"] = file_date
    for column in ("position_date", "published_from", "published_to"):
        parsed = pd.to_datetime(out[column], errors="coerce")
        out[column] = parsed.dt.date.astype(object).where(parsed.notna(), None)
    out["net_short_pct"] = pd.to_numeric(out["net_short_pct"], errors="coerce")
    for column in ("holder", "holder_lei", "issuer", "isin"):
        out[column] = out[column].astype("string").str.strip().replace({"": None}).astype(object).where(out[column].notna(), None)
    bad = out["net_short_pct"].isna() | out["position_date"].isna() | out["isin"].isna() | out["holder"].isna()
    if bad.any():
        raise RegisterError(f"{int(bad.sum())} rows without a holder, an ISIN, a position date or a percentage")
    out = out[list(COLUMNS)].sort_values(["holder", "isin", "position_date"], kind="stable").reset_index(drop=True)
    return out


def to_table(frame: pd.DataFrame) -> pa.Table:
    return pa.Table.from_pandas(frame[list(COLUMNS)], schema=SCHEMA, preserve_index=False)


# --------------------------------------------------------------------------- #
# store
# --------------------------------------------------------------------------- #
class HistoryStore:
    """One market's history file, its previous generation and its state."""

    def __init__(self, root: Path, market: str) -> None:
        self.market = market
        self.dir = Path(root) / market
        self.path = self.dir / "history.parquet"
        self.previous = self.dir / "history.prev.parquet"
        self.state_path = self.dir / "state.json"

    def exists(self) -> bool:
        return self.path.exists()

    def load_state(self) -> dict[str, Any]:
        if not self.state_path.exists():
            return {}
        return json.loads(self.state_path.read_text(encoding="utf-8"))

    def read(self) -> pd.DataFrame | None:
        if not self.path.exists():
            return None
        return pd.read_parquet(self.path)

    def write(self, frame: pd.DataFrame, state: dict[str, Any]) -> None:
        self.dir.mkdir(parents=True, exist_ok=True)
        if self.path.exists():
            _atomic.replace_with_retry(self.path, self.previous)
        _atomic.write_table(to_table(frame), self.path)
        tmp = self.state_path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")
        _atomic.replace_with_retry(tmp, self.state_path)


def store(root: Path, market: str) -> HistoryStore:
    if market not in MARKETS:
        raise RegisterError(f"unknown market {market!r}; expected one of {', '.join(MARKETS)}")
    return HistoryStore(root, market)


@dataclass(frozen=True)
class FetchReport:
    market: str
    run: bool
    root: Path
    file_date: dt.date | None
    rows: int
    outcome: str  # stored | replaced | unchanged | planned | failed
    detail: str = ""

    @property
    def ok(self) -> bool:
        return self.outcome != "failed"


Payload = bytes | dict[str, bytes]


def _parts(payload: Payload) -> list[tuple[str, bytes]]:
    if isinstance(payload, dict):
        return sorted(payload.items())
    return [("file", payload)]


def digest(payload: Payload) -> str:
    """sha256 over the named parts in name order (one file: its bytes)."""
    h = hashlib.sha256()
    for name, data in _parts(payload):
        if isinstance(payload, dict):
            h.update(name.encode("utf-8") + b"\0")
        h.update(data)
    return h.hexdigest()


def size(payload: Payload) -> int:
    return sum(len(data) for _, data in _parts(payload))


def refresh(
    market: str,
    fetch: Callable[[], tuple[Any, str]],
    parse: Callable[[Any], Parsed],
    root: Path,
    *,
    run: bool,
    now: Callable[[], dt.datetime] | None = None,
) -> FetchReport:
    """Fetch the published file(s); with ``run`` replace the stored history when they changed.

    ``fetch`` returns the raw bytes (or a dict of named parts for a register
    published as several files) and a source label. Without ``run`` the
    files are still downloaded and parsed but nothing is written.
    """
    clock = now or (lambda: dt.datetime.now(dt.timezone.utc))
    target = store(root, market)
    try:
        data, source = fetch()
        parsed = parse(data)
    except (RegisterError, OSError, ValueError, KeyError) as exc:
        return FetchReport(market, run, root, None, 0, "failed", f"{type(exc).__name__}: {exc}")
    sha = digest(data)
    state = target.load_state()
    if state.get("sha256") == sha and target.exists():
        return FetchReport(market, run, root, parsed.file_date, len(parsed.rows), "unchanged")
    stored_rows = int(state.get("rows", 0)) if target.exists() else 0
    if len(parsed.rows) < stored_rows:
        return FetchReport(
            market, run, root, parsed.file_date, len(parsed.rows), "failed",
            f"the published file has {len(parsed.rows):,} rows, fewer than the stored {stored_rows:,}: a history must not shrink",
        )
    if not run:
        return FetchReport(market, run, root, parsed.file_date, len(parsed.rows), "planned")
    replaced = target.exists()
    detail = f"file dated {parsed.file_date.isoformat()}"
    if replaced:
        detail += f"; replaced the stored file of {state.get('file_date')} ({stored_rows:,} rows)"
    target.write(
        parsed.rows,
        {
            "market": market,
            "file_date": parsed.file_date.isoformat(),
            "rows": int(len(parsed.rows)),
            "sha256": sha,
            "bytes": int(size(data)),
            "fetched_at": clock().strftime("%Y-%m-%dT%H:%M:%SZ"),
            "source": source,
            "detail": detail,
        },
    )
    return FetchReport(market, run, root, parsed.file_date, len(parsed.rows), "replaced" if replaced else "stored", detail)


def status(root: Path) -> list[dict[str, Any]]:
    out = []
    for market in MARKETS:
        target = store(root, market)
        state = target.load_state()
        present = target.exists()
        out.append(
            {
                "market": market,
                "present": present,
                "file_date": state.get("file_date") if present else None,
                "rows": int(state.get("rows", 0)) if present else 0,
                "bytes": int(state.get("bytes", 0)) if present else 0,
                "last_fetch": state.get("fetched_at") if present else None,
                "previous": target.previous.exists(),
            }
        )
    return out


def qc(root: Path, *, today: dt.date | None = None) -> list[tuple[str, str, str]]:
    """``(severity, check, detail)`` over the stored histories."""
    today = today or dt.date.today()
    findings: list[tuple[str, str, str]] = []
    any_present = False
    for market in MARKETS:
        target = store(root, market)
        if not target.exists():
            findings.append(("warn", f"{market}_empty", f"no {market} history stored; run `registers fetch --market {market} --run`"))
            continue
        any_present = True
        state = target.load_state()
        frame = target.read()
        assert frame is not None
        if int(state.get("rows", -1)) != len(frame):
            findings.append(("error", f"{market}_state_rows", f"state says {state.get('rows')} rows, the file has {len(frame):,}"))
        dupes = int(frame.duplicated().sum())
        if dupes:
            findings.append(("warn", f"{market}_duplicate_rows", f"{dupes} rows published twice (holder, ISIN, date and percentage identical)"))
        negative = int((frame["net_short_pct"] < 0).sum())
        if negative:
            findings.append(("error", f"{market}_negative", f"{negative} rows with a negative percentage"))
        future = int((pd.to_datetime(frame["position_date"]) > pd.Timestamp(today)).sum())
        if future:
            findings.append(("error", f"{market}_future", f"{future} rows with a position date after today"))
        last = pd.to_datetime(frame["position_date"]).max().date()
        stale = (today - last).days
        if stale > 7:
            findings.append(("warn", f"{market}_stale", f"the latest position date is {last.isoformat()}, {stale} days ago"))
    if not any_present:
        return [("warn", "empty", "no register history stored; run `registers fetch --run`")]
    return findings
